# Generated by Django 3.2 on 2022-06-24 12:19

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_comments_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='general/default.jpg', upload_to=product.models.general_image)),
                ('image_mobile', models.ImageField(default='general/default.jpg', upload_to=product.models.general_image)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
